{
    "general_error_message": "Le bot a rencontré une erreur, veuillez réessayer plus tard."
}